// d LOGIN
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";

// d REGISTRO
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";

// d ALERTA
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

// d PRODUCTOS
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const PRODUCTO_SELECCIONADO = "PRODUCTO_SELECCIONADO";
export const PRODUCTOS_LISTA = "PRODUCTOS_LISTA";
export const OBTENER_PRODUCTOS_CATEGORIAS = "OBTENER_PRODUCTOS_CATEGORIAS";
export const OBTENER_PRODUCTOS_CLIENTE = "OBTENER_PRODUCTOS_CLIENTE";
export const PRODUCTOS_ERROR = "PRODUCTOS_ERROR";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const OBTENER_PRODUCTOS_AGOTADOS = "OBTENER_PRODUCTOS_AGOTADOS";
export const LIMPIAR = "LIMPIAR";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const LIMPIAR_PRODUCTO_ELEJIDO = "LIMPIAR_PRODUCTO_ELEJIDO";
export const MANTENER_ESTADO = "MANTENER_ESTADO";

// d PEDIDOS
export const OBTENER_PEDIDOS = "OBTENER_PEDIDOS";
export const PEDIDO_SELECCIONADO = "PEDIDO_SELECCIONADO";

// d reclamos
export const OBTENER_RECLAMOS = "OBTENER_RECLAMOS";
export const SELECCIONAR_REACLAMO = "SELECCIONAR_REACLAMO";

// d usuarios
export const REGISTRAR_USUARIOS = "REGISTRAR_USUARIOS";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const SELECCIONAR_USUARIO = "SELECCIONAR_USUARIO";
export const USUARIO_ERROR = "USUARIO_ERROR";
export const SELECCIONAR_USUARIO_PEDIDO = "SELECCIONAR_USUARIO_PEDIDO";
export const REMOVER_USUARIO_PEDIDO = "REMOVER_USUARIO_PEDIDO";

// d lista
export const AGREGAR_PRODUCTOS = "AGREGAR_PRODUCTOS";
export const QUITAR_PRODUCTOS = "QUITAR_PRODUCTOS";
export const SELECIONAR_ITEM = "SELECIONAR_ITEM";
export const ACTUALIZAR_ITEM = "ACTUALIZAR_ITEM";
export const OBTENER_LISTA_CREADA = "OBTENER_LISTA_CREADA";
export const ELIMINAR_LISTA = "ELIMINAR_LISTA";

// d DB storage
export const OBTENER_LISTAS = "OBTENER_LISTAS";

// Direcciones
export const OBTENER_DIRECCIONES = "OBTENER_DIRECCIONES";
export const ACTUALIZAR_DIRECCION = "ACTUALIZAR_DIRECCION";
export const SELECCIONAR_DIRECCION = "SELECCIONAR_DIRECCION";
export const CREAR_NUEVA_DIRECCION = "CREAR_NUEVA_DIRECCION";
export const REMOVER_DIRECCION_SELECCIONADA = "REMOVER_DIRECCION_SELECCIONADA";
